scrape_configs:
  - job_name: 'flask_application'
    scrape_interval: 10s  # Modify based on your needs
    static_configs:
      - targets: ['localhost:5000']  # Adjust the host and port if needed
